on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Linux Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Protobuf
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq protobuf-compiler

    - name: Update submodules
      run: |
        git submodule init
        git submodule update --remote --merge

    - uses: arduino/setup-protoc@v1
    - uses: bufbuild/buf-setup-action@v0.7.0
    - uses: bufbuild/buf-lint-action@v1
      with:
        input: 'substrait'

    - name: Build
      run: make

    - name: Test
      run: build/tests/unit_test