on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: DuckDB/Substrait Integration
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Protobuf and Ninja
      run: brew update && brew install protobuf && brew install ninja

    - name: Update submodules
      run: |
        git submodule init
        git submodule update --remote --merge

    - uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: bufbuild/buf-setup-action@v0.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: bufbuild/buf-lint-action@v1
      with:
        input: 'substrait'

    - name: Build
      run: make main

    - name: Test
      run: build/tests/unit_test