on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Linux Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Protobuf
      run: PROTOC_ZIP=protoc-3.19.2-linux-x86_64.zip && curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.19.2/$PROTOC_ZIP && sudo unzip $PROTOC_ZIP -d $HOME/.local && echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Update submodules
      run: |
        git submodule init
        git submodule update --remote --merge

    - uses: arduino/setup-protoc@v1
    - uses: bufbuild/buf-setup-action@v0.7.0
    - uses: bufbuild/buf-lint-action@v1
      with:
        input: 'substrait'

    - name: Build
      run: make

    - name: Test
      run: build/tests/unit_test